
services:
  db:
    image: postgres:latest
    hostname: ${DB_HOST}
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest  # You can specify a version like redis:7.0 if needed
    ports:
      - "6379:6379"  # Expose Redis on port 6379
    volumes:
      - redisdata:/data  # Optional: Persist Redis data

volumes:
  pgdata:
  redisdata:  # Optional: Define a volume for Redis data
